export const homeState_dev = {
    categoryListDropdown: false,
    filterListDropdown: false,
    searchDropdown: false,
    products: null,
    loading: false,
    sliderImages: [],
  };


  export const layoutState_dev = {
    navberHamburger: false,
    loginSignupModal: false,
    loginSignupError: false,
    cartModal: false,
    cartProduct: null,
    singleProductDetail: null,
    inCart: null,
    cartTotalCost: null,
    orderSuccess: false,
    loading: false,
  };
  

  export const categoryState = {
    categories: [],
    addCategoryModal: false,
    editCategoryModal: {
      modal: false,
      cId: null,
      des: "",
      status: "",
    },
    loading: false,
  };


export const productState = {
  products: null,
  addProductModal: false,
  editProductModal: {
    modal: false,
    pId: "",
    pName: "",
    pDescription: "",
    pImages: null,
    pStatus: "",
    pCategory: "",
    pQuantity: "",
    pPrice: "",
    pOffer: "",
  },}
  
  export const productState = {
  products: null,
  addProductModal: false,
  editProductModal: {
    modal: false,
    pId: "",
    pName: "",
    pDescription: "",
    pImages: null,
    pStatus: "",
    pCategory: "",
    pQuantity: "",
    pPrice: "",
    pOffer: "",
  },}
  
  
  export const productState = {
  products: null,
  addProductModal: false,
  editProductModal: {
    modal: false,
    pId: "",
    pName: "",
    pDescription: "",
    pImages: null,
    pStatus: "",
    pCategory: "",
    pQuantity: "",
    pPrice: "",
    pOffer: "",
  },}

  export const productState = {
    products: null,
    addProductModal: false,
    editProductModal: {
      modal: false,
      pId: "",
      pName: "",
      pDescription: "",
      pImages: null,
      pStatus: "",
      pCategory: "",
      pQuantity: "",
      pPrice: "",
      pOffer: "",
    },
}
//to be connected

export const layoutState_dev = {
    navberHamburger: false,
    loginSignupModal: false,
    loginSignupError: false,
    cartModal: false,
    cartProduct: null,
    singleProductDetail: null,
    inCart: null,
    cartTotalCost: null,
    orderSuccess: false,
    loading: false,
  };



export const productDetailsState = {
    loading: false,
    menu: true,
  };//menu,loading,cartState


  /**


we will let the hospotals signup, and add their services,
but will not be shown without the admin approval,


reviews can be made if wanted


google: reviews,
instegram: reviews,
facebook: reviews,
prices:
hair:
tummy:
dental: 1 crown, implant, sinuslift

Or range prices with reviews by private to be sent.
30 choices, and our recommend, 
5 dollars in return 5% discount on the chosen option

*/


